[experiment]

weekly = [
  "ad_clicks",
  "searches_with_ads",
  "tagged_search_count",
]

overall = [
  "ad_clicks",
  "searches_with_ads",
  "tagged_search_count",
]

preenrollment_weekly = [
  "ad_clicks",
  "searches_with_ads",
  "tagged_search_count",
]

[metrics.ad_clicks.statistics.linear_model_mean]
[metrics.ad_clicks.statistics.linear_model_mean.covariate_adjustment]
period = "preenrollment_week"
[metrics.ad_clicks.statistics.deciles]

[metrics.searches_with_ads.statistics.linear_model_mean]
[metrics.searches_with_ads.statistics.linear_model_mean.covariate_adjustment]
period = "preenrollment_week"
[metrics.searches_with_ads.statistics.deciles]

[metrics.tagged_search_count.statistics.linear_model_mean]
[metrics.tagged_search_count.statistics.linear_model_mean.covariate_adjustment]
period = "preenrollment_week"
[metrics.tagged_search_count.statistics.deciles]