[experiment]
enrollment_period = 0

enrollment_query = """
  SELECT
      e.profile_group_id AS analysis_id,
      `mozfun.map.get_key`(e.event_map_values, 'branch')
          AS branch,
      MIN(e.submission_date) AS enrollment_date,
      COUNT(e.submission_date) AS num_enrollment_events
  FROM
      `moz-fx-data-shared-prod.telemetry.events` e
  WHERE
      e.event_category = 'normandy'
      AND e.event_method = 'enroll'
      AND e.submission_date
          BETWEEN '2026-01-07' AND '2026-09-16'
      AND e.event_string_value = 'long-term-holdback-2026-growth-desktop'
      AND (
        (`mozfun.map.get_key`(e.event_map_values, 'branch') = 'holdback'
          AND MOD(ABS(FARM_FINGERPRINT(e.profile_group_id)), 10000) < 1450)
        OR (`mozfun.map.get_key`(e.event_map_values, 'branch') = 'delivery'
          AND MOD(ABS(FARM_FINGERPRINT(e.profile_group_id)), 10000) < 76)
      )
  GROUP BY ALL
"""
