[experiment]
segments = ['playstore']

[segments.playstore]
data_source = "baseline"
friendly_name = "Play Store Installs"
description = "Clients who installed from the Play Store (com.android.vending)"
select_expression = """COALESCE(CAST(MAX(CASE WHEN metrics.string.first_session_install_source = 'com.android.vending' THEN 1 ELSE 0 END) AS BOOL), FALSE)"""


[segments.data_sources.baseline]
from_expression = """(SELECT metrics.string.first_session_install_source,client_info.client_id as client_id, DATE(p.submission_timestamp) AS submission_date FROM `moz-fx-data-shared-prod.org_mozilla_firefox.baseline` p )"""


