[metrics]

weekly = ["privacy_panel_clicks"]
overall = ["privacy_panel_clicks"]

# Metric for total number of privacy panel clicks
[metrics.privacy_panel_clicks]
 select_expression = """
  COALESCE(SUM(CASE
    WHEN event_category = 'security.ui.protectionspopup'
    AND event_method = 'open'
    AND event_object = 'protections_popup'
    THEN 1
    ELSE 0
  END), 0)
  """

data_source = "security_events"
friendly_name = "Privacy Panel Clicks"
description = "Total number of times users opened the protections popup"

[metrics.privacy_panel_clicks.statistics.bootstrap_mean]

[metrics.privacy_panel_clicks.statistics.deciles]

[data_sources.security_events]
  from_expression = """
  (
    SELECT
      *
    FROM `moz-fx-data-shared-prod.telemetry.events`
    WHERE event_category = 'security.ui.protectionspopup'
  )
  """
  experiments_column_type = "native"
  friendly_name = "Security UI Events"
  description = "Events from the security.ui.protectionspopup category"