[metrics]

weekly = ["privacy_panel_clicks"]
overall = ["privacy_panel_clicks"]

# Metric for total number of privacy panel clicks
[metrics.privacy_panel_clicks]
select_expression = """
COALESCE(SUM(CASE 
  WHEN event_category = 'security.ui.protectionspopup' 
  AND event_name = 'open_protections_popup' 
  THEN 1 
  ELSE 0 
END), 0)
"""
data_source = "events_unnested"
friendly_name = "Privacy Panel Clicks"
description = "Total number of times users opened the protections popup"
bigger_is_better = true

[metrics.privacy_panel_clicks.statistics.bootstrap_mean]

[metrics.privacy_panel_clicks.statistics.deciles]

[data_sources.events_unnested]
from_expression = """
( SELECT
        legacy_telemetry_client_id AS client_id,
        profile_group_id,
        DATE(submission_timestamp) AS submission_date,
        experiments,
        event_name,
        event_extra,
    FROM `mozdata.firefox_desktop.events_stream`
WHERE event_category = 'security.ui.protectionspopup' )
"""
