[metrics]

weekly = ["smart_window_call_out_click", "smart_window_adoption", "land_in_smart_window", "smart_window_activation"]
overall = ["smart_window_call_out_click", "smart_window_adoption", "land_in_smart_window", "smart_window_activation"]

[metrics.smart_window_call_out_click]
friendly_name = "Smart Window Feature Callout Click Rate"
description = "Rate of Users who clicked on the Smart Window Feature Callout."
data_source = "smart_window_feature_callout"
select_expression = "LOGICAL_OR(COALESCE(event = 'CLICK_BUTTON' AND event_source = 'primary_button', FALSE))"

[metrics.land_in_smart_window]
friendly_name = "Land In Smart Window User rate"
description = "Rate of Users who land in Smart Window."
data_source = "smart_window_onboarding"
select_expression = "LOGICAL_OR(COALESCE(event_name = 'onboarding_screen_impression', FALSE))"

[metrics.smart_window_adoption]
friendly_name = "Smart Window Adoption"
description = "Users who completed Smart Window Onboarding."
data_source = "smart_window_onboarding"
select_expression = "LOGICAL_OR(COALESCE(event_name = 'onboarding_complete', FALSE))"

[metrics.smart_window_activation]
friendly_name = "Smart Window Activation"
description = "Users who did a meaningful action in Smart Window."
data_source = "smart_window_onboarding"
select_expression = "LOGICAL_OR(COALESCE(event_name IN ('uri_load', 'chat_submit'), FALSE))"

[metrics.smart_window_call_out_click.statistics.binomial]
[metrics.land_in_smart_window.statistics.binomial]
[metrics.smart_window_adoption.statistics.binomial]
[metrics.smart_window_activation.statistics.binomial]

[data_sources]

[data_sources.smart_window_onboarding]
from_expression = """(
  SELECT
    *,
    DATE(submission_timestamp) AS submission_date
  FROM 
    `moz-fx-data-shared-prod.firefox_desktop.events_stream`
  WHERE 
    event_category = 'smart_window'
    AND event_name IN ('onboarding_screen_impression', 'onboarding_complete', 'uri_load', 'chat_submit')
)"""
description = "Glean events_stream (one row per event) filtered to smart Window Onboarding"
friendly_name = "Glean Events Stream Filtered (Smart Window Onboarding)"
experiments_column_type = "none"
client_id_column = "client_id"

[data_sources.smart_window_feature_callout]
from_expression = """(
  SELECT
    DATE(submission_timestamp) AS submission_date,
    *
  FROM `moz-fx-data-shared-prod.firefox_desktop.onboarding`
  WHERE 
    event = 'CLICK_BUTTON'
    AND event_source = 'primary_button'
    AND message_id LIKE '%SMARTWINDOW_SHOPPING_DOMAIN%'
)"""
description = "Messaging System Feature callout for Smart Window Shopping domain callout"
friendly_name = "Messaging system filtered (Smart window shopping domain)"
experiments_column_type = "none"
client_id_column = "client_id"