## No overrides of existing configuration settings; just adding one custom metric
##  for feature-specific usage

[metrics]

daily = ["split_view_usage"]

weekly = ["split_view_usage"]

overall = ["split_view_usage"]

[metrics.split_view_usage]
select_expression = "COALESCE(LOGICAL_OR(mozfun.map.extract_keyed_scalar_sum(splitview_uri_count) > 0), FALSE)"
data_source = "split_view_metrics"
friendly_name = "Split-view feature DAU"
description = "The number of unique daily clients loading at least one URI in a split view tab pane (either side)."

[metrics.split_view_usage.statistics.binomial]

[data_sources]

[data_sources.split_view_metrics]
from_expression = """(
    SELECT
        DATE(submission_timestamp) AS submission_date,
        metrics.uuid.legacy_telemetry_client_id AS client_id,
        metrics.uuid.legacy_telemetry_profile_group_id AS profile_group_id,
        ping_info,
        metrics.labeled_counter.splitview_uri_count AS splitview_uri_count
    FROM
        `mozdata.firefox_desktop.metrics` 
)"""
client_id_column = "client_id"
experiments_column_type = "glean"